FROM bellsoft/liberica-native-image-kit-container:jdk-17-nik-22-musl
COPY target/CoinCapConsumer-0.0.1-SNAPSHOT.jar CoinCapConsumer-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/CoinCapConsumer-0.0.1-SNAPSHOT.jar"]